image: gitpod/workspace-postgres

tasks:
  - init: npm install
    command: |
      export HMR_HOST=`gp url 3000` 
      echo "Starting dev server.."
      npm run dev

ports:
  - port: 3000
    onOpen: open-browser
  - port: 5432
    onOpen: ignore 

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    
vscode:
  extensions:
    - svelte.svelte-vscode
